=== SambodhanRai/Lab-report2/html/sambodhanrai_15_25.dtd
<!ELEMENT catalog (book+)>
<!ELEMENT book (author, title, genre, price)>
<!ATTLIST book id ID #REQUIRED>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== SambodhanRai/Lab-report2/html/sambodhanrai_15_24.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "sambodhanrai_15_25.dtd">
<catalog>
    <book id="bk101">
        <author>Jk Rowling</author>
        <title>Harry Potter and the Philosophers Stone</title>
        <genre>Fantasy</genre>
        <price>44.99</price>
    </book>
    <book id="bk102">
        <author>Ralls, Kim</author>
        <title>Midnight Rain</title>
        <genre>Fantasy</genre>
        <price>5.95</price>
    </book>
</catalog>
